language: python
sudo: true
python:
  - "3.7.3"
cache: pip
install:
  - pip3 install -r requirements.txt
  - nvm install 10
  - npm install -g jscpd
  - sudo apt-get install ctags
  - export PATH="$PATH:/usr/bin/ctags"
  - ctags --version
jobs:
  include:
    - stage: "Static Analysis"
      name: "static analysis 'pylint & JSCPD'"
      script:
        - pylint functiondefextractor/ test/
        - jscpd --min-tokens 20 --reporters "json" --mode "strict" --format "python" -o . .
        - python3 test_resource/jscpd_parser.py --j 10 #Allowed duplication is 10% with 20 token size
    - stage: "Tests & Coverage"
      name: "Unit and functional test with coverage"
      script:
        - python3 -m pytest -v
        - pytest --cov-config=.coveragerc --cov=functiondefextractor
        - coverage report --fail-under=85 #Coverage should be above 90%
      after_success: codecov

    - stage: "Mutation Tests"
      name: "mutation testing using mutmut"
      script:
        - mutmut --paths-to-mutate "functiondefextractor" run || true
        - mutmut junitxml --suspicious-policy=ignore --untested-policy=ignore > mutmut.xml
        - python3 test_resource/mutmut_parse.py --m 30 #Mutation (failure+disables+error) allowed 30% of total mutants

